experiment_name: experiment_asd1_asd2_mixed_first3_st5_mfcc
dataset_type: mixed
datadir: /srv/storage/talc@storage4.nancy/multispeech/corpus/speech_production/iadi/ArtSpeech_Database_2
asd1_datadir: /srv/storage/talc@storage4.nancy/multispeech/corpus/speech_production/iadi/ArtSpeech_Database_1_raw
asd2_datadir: /srv/storage/talc@storage4.nancy/multispeech/corpus/speech_production/iadi/ArtSpeech_Database_2
asd1_annotation_dir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/bf/inference
phonemesdir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/inversion_single_task5_minimal/config/list_phonemes.json
data_save: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/inversion_single_task5_minimal
folder_save: asd1_asd2_mixed_first3_st5_mfcc
n_epochs: 1
batch_size: 8
learning_rate: 0.001
weight_decay: 0.001
optimizer: adam
patience: 5
save_every: 1
num_layers: 1
input_layer: 39
hidden_layer: 300
output_layer: 100
context_window: 0
sequence_length: 80
added_frames: 20
ms_image: 19.98
n_mfcc: 13
hop_length_ratio: 10
window_length_ms: 25
skip_ms: 400
nbr_phonemes: 1
phonemes: false
alpha: 1
loss_function: mse_all_articulators_full_asd2_single_task5
mode: train
model: single_task5_asd1_asd2_mixed_first3_1epoch
tag: single_task5_asd1_asd2_mixed_first3_1epoch
classes:
- arytenoid-cartilage
- epiglottis
- lower-lip
- pharynx
- soft-palate-midline
- tongue
- upper-lip
- vocal-folds
train_sequences:
  P1:
  - S1
  '1775':
  - S6
valid_sequences:
  P1:
  - S3
  '1775':
  - S7
test_sequences:
  P1:
  - S6
  '1775':
  - S8
inference_sequences:
  P1:
  - S6
  '1775':
  - S8
input_type: mfcc
phoneme_tier_index: 1
skip_outlier_detection: true
skip_test_plots: true
skip_tract_variables: true
use_mri: false
cache_dataset: true
rebuild_dataset_cache: false
dataset_cache_dir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/inversion_single_task5_minimal/repro/asd1_asd2_mixed_first3_st5_mfcc/cache
load_labels_progress_every: 1
max_chunks_per_session: 5
num_workers: 4
pin_memory: true
persistent_workers: true
prefetch_factor: 2
