experiment_name: experiment_asd2_smoke_2train_1val_1test_st5_mfcc_2gpu
datadir: /srv/storage/talc@storage4.nancy/multispeech/corpus/speech_production/iadi/ArtSpeech_Database_2
phonemesdir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/inversion_single_task5_minimal/config/list_phonemes.json
data_save: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/inversion_single_task5_minimal
folder_save: asd2_smoke_2train_1val_1test_st5_mfcc_2gpu
n_epochs: 2
batch_size: 10
learning_rate: 0.001
weight_decay: 0.001
optimizer: adam
patience: 5
save_every: 1
num_layers: 1
input_layer: 39
hidden_layer: 300
output_layer: 100
context_window: 0
sequence_length: 80
added_frames: 20
ms_image: 19.98
n_mfcc: 13
hop_length_ratio: 10
window_length_ms: 25
skip_ms: 400
nbr_phonemes: 1
phonemes: false
alpha: 1
loss_function: mse_all_articulators_full_asd2_single_task5
mode: train
model: single_task5_smoke_2train_1val_1test_st5_mfcc_2gpu_2epoch
tag: single_task5_smoke_2train_1val_1test_st5_mfcc_2gpu_2epoch
classes:
- arytenoid-cartilage
- epiglottis
- lower-lip
- pharynx
- soft-palate-midline
- tongue
- upper-lip
- vocal-folds
train_sequences:
  '1775':
  - S6
  - S7
valid_sequences:
  '1775':
  - S29
test_sequences:
  '1775':
  - S37
inference_sequences:
  '1775':
  - S37
input_type: mfcc
skip_outlier_detection: true
skip_test_plots: true
skip_tract_variables: true
use_mri: false
cache_dataset: true
rebuild_dataset_cache: false
dataset_cache_dir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/nhanguyen/inversion_single_task5_minimal/repro/asd2_smoke_2train_1val_1test_st5_mfcc_2gpu/cache
load_labels_progress_every: 10
